---
title: "inclass-4"
author: "Joseph Davis Chamdani"
date: "2025-10-13"
output: html_document
---

```{r}
a <- c(1,2,3,4)
a
```
```{r}
a*2
```


```{r}
b <- c(10,20,30,40)
a*b
```
```{r}
"hi!"
```
```{r}
1:100
```
```{r}
a
length(a)
```
```{r}
colors <- c("purple", "gold", "blue")
colors
```
```{r}
1:10
```
```{r}
colors2 <- c("gray","lawngreen","pink")
colors2
```
```{r}
allColor <- c(colors, colors2)
allColor
```
```{r}
s <- c()
for(n in 1:10) {
  s <- c(s, n^2)
}
s
```
```{r}
(1:10)^2
```
```{r}
v1 <- c(1,1,1)
v2 <- c(1,2,3)
v1+v2
v1*v2
(v1+v2)/(v1+v1)
```
```{r}
money <- c(100,200,300)
price <- c(50,150,250)
money >= 200 & price <= 200
```

```{r}
customer_age <- c(16,20,24)
cashier_name <- c("Yu Huang", "Guanyin", "Yu Huang")

customer_age >=21 | cashier_name == "Guanyin"
```
```{r}
sqrt(1:10)
```
```{r}
sum (1:10)
```
```{r}
sum(1:1000)
```
```{r}
min(c(1,3,6,-5))
```
```{r}
range(c(1,5,4,3,-1,6,7))
```
```{r}
colors
```

```{r}
colors [c(1,3)]
```
```{r}
incomes <- c(30,45,70,110,55)
idx <- c(1,2,5)
incomes [idx]
```
```{r}
incomes <- c(30,45,70,110,55)
idx <- c(TRUE, TRUE, FALSE, FALSE, TRUE)
incomes [idx]
```

```{r}
incomes <- c(30,45,70,110,55)
idx <- incomes < 60
print(idx)
incomes[idx]
```

```{r}
incomes [incomes < 60]
```

```{r}
numbers <- 1:20
numbers[numbers %% 2 == 1]
```
```{r}
height <- c(160,170,180,190,175) #cm
weight <- c (50,60,70,80,90) #kg
name <- c("Kannika", "Nan", "Nin", "Kasem", "Panya")

#Height >= 180 cm
height[height >= 180]

#Name >= 180 cm
name[height >= 180]

#weight >= cm
weight[height >= 180]

#name < 70 kg
name[weight < 70]

#name > 170 cm | weight > 70 kg
name[height > 170 | weight > 70]

```
```{r}
colors[3] <- "skyblue"
colors
```
```{r}
incomes
```
```{r}
incomes[incomes>60] <- 60
incomes
```
```{r}
incomes[incomes < 60] <- 1.1*incomes[incomes < 60]
incomes
```

